name: Docker - Build & Publish (Manual)

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/todo-app

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag or fallback to latest
        id: version
        run: |
          VERSION=${GITHUB_REF##*/}
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }} ./backend/

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}