name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run Unit and Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: ./backend
        run: dotnet restore

      - name: Run Unit Tests
        working-directory: ./backend
        run: dotnet test Todo.Application.Tests/ --verbosity normal

      - name: Run Integration Tests
        working-directory: ./backend
        run: dotnet test Todo.Infrastructure.Tests/ --verbosity normal